WhatsCookinGroupCapstone/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhatsCookinGroupCapstone.Contracts;
using WhatsCookinGroupCapstone.Data;
using WhatsCookinGroupCapstone.Models;

namespace WhatsCookinGroupCapstone.Controllers
{
    public class RecipeController : Controller
    {
        private IRepositoryWrapper _repo;

        public RecipeController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        // GET: Recipe
        public IActionResult Index()
        {
            List<Recipe> myRecipeList = new List<Recipe>();

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var loggedInCook = _repo.Cook.FindByCondition(e => e.IdentityUserId == userId).SingleOrDefault();
            var loggedInCookID = loggedInCook.CookId;
            myRecipeList = _repo.Recipe.FindByCondition(r => r.CookID == loggedInCookID).ToList();

            return View(myRecipeList);
        }

        // GET: Recipe/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();

            if (recipe == null)
            {
                return NotFound();
            }


            return View(recipe);
        }

        // GET: Recipe/Create
        public IActionResult Create()
        {
            Recipe recipe = new Recipe();
            {
                recipe.AllTags = GetTags();
            }
            return View(recipe);
        }

        // POST: Recipe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var loggedInCook = _repo.Cook.FindByCondition(e => e.IdentityUserId == userId).SingleOrDefault();
                var loggedInCookID = loggedInCook.CookId;
                recipe.CookID = loggedInCookID ;
                _repo.Recipe.Create(recipe);
                _repo.Save();

                //This is where the tags are bound to the recipe by the cook.
                var selectedRecipe = _repo.Recipe.FindByCondition(r => r.RecipeId == recipe.RecipeId).SingleOrDefault();
                var selectedRecipeId = selectedRecipe.RecipeId;

                foreach(string tags in recipe.SelectedTags)
                {
                    var selectedTags = _repo.Tags.FindByCondition(r => r.Name == tags).SingleOrDefault();

                    RecipeTags recipeTags = new RecipeTags();
                    recipeTags.RecipeId = selectedRecipeId;
                    recipeTags.TagsId = selectedTags.TagsId;
                    _repo.RecipeTags.Create(recipeTags);
                    _repo.Save();
                }




                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipe/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();
            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        // POST: Recipe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("RecipeId,RecipeName,IMGUrl,Ingredients,Description,Steps,CookID")] Recipe recipe)
        {
            if (id != recipe.RecipeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Recipe.Update(recipe);
                    _repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.RecipeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipe/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = _repo.Recipe
                .FindByCondition(m => m.RecipeId == id).FirstOrDefault();
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var recipe =  _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();
            //This code might cause a future problem
            _repo.Recipe.Delete(recipe);
            _repo.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
            var foundRecip = _repo.Recipe.FindByCondition(r => r.RecipeId == id);
            if(foundRecip == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        // GET: All Recipes
        //public IActionResult Search()
        //{
        //    var allRecipes = _repo.Recipe.FindAll();

        //    return View(allRecipes);
        //}

        //public IActionResult Saved(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var recipe = _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();
        //    if (recipe == null)
        //    {
        //        return NotFound();
        //    }
        //    return View();
        //}

        private IList<SelectListItem> GetTags()
        {
            return new List<SelectListItem>
            {
                new SelectListItem { Text = "Vegan", Value = "Vegan" },
                new SelectListItem { Text = "Paleo", Value = "Paleo" },
                new SelectListItem { Text = "Pescatarian", Value = "Pescatarian" },
                new SelectListItem { Text = "Nut-Free", Value = "Nut-Free" },
                new SelectListItem { Text = "Dairy", Value = "Dairy" }
            };

       }
    }
}

WhatsCookinGroupCapstone/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhatsCookinGroupCapstone.Contracts;
using WhatsCookinGroupCapstone.Data;
using WhatsCookinGroupCapstone.Models;

namespace WhatsCookinGroupCapstone.Controllers
{
    public class RecipesController : Controller
    {
        private readonly IRepositoryWrapper _repo;

        public RecipesController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        // GET: Recipes
        public async Task<IActionResult> Index()
        {
            List<Recipe> myRecipeList = new List<Recipe>();

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var loggedInCook =  _repo.Cook.FindByCondition(e => e.IdentityUserId == userId).SingleOrDefault();
            var loggedInCookID = loggedInCook.CookId;
            myRecipeList = await _repo.Recipe.FindByCondition(r => r.CookID == loggedInCookID).ToListAsync();

            return View(myRecipeList);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            Recipe recipe = new Recipe();
            {
                recipe.AllTags = GetTags();
            }
            return View(recipe);
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var loggedInCook = await _repo.Cook.FindByCondition(e => e.IdentityUserId == userId).SingleOrDefaultAsync();
                var loggedInCookID = loggedInCook.CookId;
                recipe.CookID = loggedInCookID;
                recipe.CookName = loggedInCook.UserName;
                _repo.Recipe.Create(recipe);
                _repo.Save();

                //This is where the tags are bound to the recipe by the cook.
                var selectedRecipe = await _repo.Recipe.FindByCondition(r => r.RecipeId == recipe.RecipeId).SingleOrDefaultAsync();
                var selectedRecipeId = selectedRecipe.RecipeId;

                foreach(string tags in recipe.SelectedTags)
                {
                    var selectedTags = await _repo.Tags.FindByCondition(r => r.Name == tags).SingleOrDefaultAsync();

                    RecipeTags recipeTags = new RecipeTags();
                    recipeTags.RecipeId = selectedRecipeId;
                    recipeTags.TagsId = selectedTags.TagsId;
                    _repo.RecipeTags.Create(recipeTags);
                    _repo.Save();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefaultAsync();

            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("RecipeId,RecipeName,IMGUrl,Ingredients,Description,Steps,CookID")] Recipe recipe)
        {
            if (id != recipe.RecipeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Recipe.Update(recipe);
                    _repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.RecipeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _repo.Recipe
                .FindByCondition(m => m.RecipeId == id).FirstOrDefaultAsync();

            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipe =  await _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefaultAsync();
            //This code might cause a future problem
            _repo.Recipe.Delete(recipe);
            _repo.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
            var foundRecip = _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();
            if(foundRecip == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

      //  GET: All Recipes
        public async Task<IActionResult> Search(string searchString)
        {
            var allRecipes = _repo.Recipe.FindAll();


          //  var AllRecipes = from r in _repo.Recipe.FindAll()
            //             select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                allRecipes = allRecipes.Where(a => a.RecipeName.Contains(searchString));
            }

            return View(await allRecipes.ToListAsync());
        }
        [HttpPost]
        public string Search(string searchString, bool notUsed)
        {
            return "From [HttpPost]Search: filter on " + searchString;
        }

        public async Task<IActionResult> CooksSaved()
        {
            CookSavedRecipes saveRecipe = new CookSavedRecipes()
            {
                AllRecipes = new List<Recipe>()
            };
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundCook = await _repo.Cook.FindByCondition(r => r.IdentityUserId == userId).SingleOrDefaultAsync();
         
            if (foundCook == null)
            {
                return NotFound();

            }
            
            var cookSavedRecipes = await _repo.CookSavedRecipes.FindByCondition(s => s.CookId == foundCook.CookId).ToListAsync();
           
            foreach (CookSavedRecipes savedRecipe in cookSavedRecipes)
            {
                var recipe = await _repo.Recipe.FindByCondition(r => r.RecipeId == savedRecipe.RecipeId).SingleOrDefaultAsync();
                saveRecipe.AllRecipes.Add(recipe);
            }
            return View(saveRecipe);
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefaultAsync();

            if (recipe == null)
            {
                return NotFound();
            }


            return View(recipe);
        }

        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]


        public async Task<IActionResult> Details(int id)
        {
            var recipe = _repo.Recipe.FindByCondition(r => r.RecipeId == id).FirstOrDefault();

            CookSavedRecipes saveRecipe = new CookSavedRecipes();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var foundCook = await _repo.Cook.FindByCondition(r => r.IdentityUserId == userId).SingleOrDefaultAsync();
            var foundRecipe = await _repo.Recipe.FindByCondition(r => r.RecipeId == recipe.RecipeId).FirstOrDefaultAsync();
            

            if (foundCook == null)
            {
                return NotFound();

            }
            saveRecipe.CookId = foundCook.CookId;
            saveRecipe.RecipeId = foundRecipe.RecipeId;

            //If they own it redirect them
            var cookOwnsThisRecipe = _repo.CookSavedRecipes.FindByCondition(s => s.CookId == foundRecipe.CookID).FirstOrDefault();
            if(cookOwnsThisRecipe != null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                var alreadySaved1 = _repo.CookSavedRecipes.FindByCondition(s => s.RecipeId == foundRecipe.RecipeId).ToList();
                foreach (CookSavedRecipes recip in alreadySaved1)
                {
                    if (foundCook.CookId == recip.CookId)
                    {
                        return RedirectToAction(nameof(CooksSaved));
                    }
                }
            }
            catch
            {
                SaveToRepo(recipe, saveRecipe);
            }

            SaveToRepo(recipe, saveRecipe);

            return RedirectToAction(nameof(CooksSaved));

        }

WhatsCookinGroupCapstone/Views/Recipes/CooksSaved.cshtml
@model WhatsCookinGroupCapstone.Models.CookSavedRecipes

@{
    ViewData["Title"] = "CooksSaves";
}

<h1  style="font-family: 'Cookie', cursive; font-weight: 600; font-size: 50px; text-align: center;">Your Saved Recipes!</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.AllRecipes.RecipeName)*@
                Recipe Name
            </th>
                @*@Html.DisplayNameFor(model => model.IMGUrl)*@
            <th>
                @*@Html.DisplayNameFor(model => model.Ingredients)*@
                Ingredients
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Description)*@
                Description
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Steps)*@
                Steps
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Cook)*@
                Cook
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.AllRecipes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RecipeName)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IMGUrl)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Ingredients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Steps)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CookName)
            </td>
            @*<td>
                <a asp-action="Details" asp-route-id="@item.RecipeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RecipeId">Delete</a>
            </td>*@
            <td>
                @*<a asp-action="Review" asp-route-id="@item.RecipeId">Submit Review</a> |
                 <a asp-action="SeeReviews" asp-route-id="@item.RecipeId">See Reviews</a>*@ 
            </td>
        </tr>
}
    </tbody>
</table>

WhatsCookinGroupCapstone/Views/Recipes/CooksSavedRecipes.cshtml
@model IEnumerable<WhatsCookinGroupCapstone.Models.Recipe>

@{
    ViewData["Title"] = "CooksSavedRecipes";
}

<h1>CooksSavedRecipes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMGUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Steps)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cook.UserName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RecipeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IMGUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Steps)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cook.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RecipeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RecipeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RecipeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WhatsCookinGroupCapstone/Views/Recipes/Create.cshtml
@model WhatsCookinGroupCapstone.Models.Recipe

@{
    ViewData["Title"] = "Create";
}

<h1 style="font-family: 'Cookie', cursive; font-weight: 600; font-size: 50px;">Create</h1>


<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMGUrl" class="control-label"></label>
                <input asp-for="IMGUrl" class="form-control" />
                <span asp-validation-for="IMGUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredients" class="control-label"></label>
                <input asp-for="Ingredients" class="form-control" />
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Steps" class="control-label"></label>
                <input asp-for="Steps" class="form-control" />
                <span asp-validation-for="Steps" class="text-danger"></span>
            </div>
            <div class="container">
                @using (Html.BeginForm("Index", "Home"))
                {
                    foreach (var item in Model.AllTags)
                    {
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"
                                       name="SelectedTags"
                                       value="@item.Value"
                                       @if (Model.SelectedTags.Contains(item.Value)) { <text> checked </text> } /> @item.Text
                                </label>
                            </div>
                        }
                        <div class="form-group text-center">
                            <input type="submit" class="btn btn-primary" style="float:left; margin: 20px 0 20px 0; " value="Submit" />
                        </div>
                    }
            </div>
            <input type="hidden" asp-for="CookID" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WhatsCookinGroupCapstone/Views/Recipes/Index.cshtml
@model IEnumerable<WhatsCookinGroupCapstone.Models.Recipe>
@*The users Cookbook*@
@{
    ViewData["Title"] = "Index";
}
<head>
    <link rel="stylesheet" type="text/css" media="screen" runat="server" href="~/css/StyleSheet.css" />

</head>
<h1 style="font-family: 'Cookie', cursive; text-align: center; font-weight: 600; font-size: 50px;">Your Recipes!</h1>
<h5 style="text-align: center">To add a new Recipe click <i>"Create"</i> down below!</h5>
<p>
    <div class="container" style="text-align:center;">

        <input type="button" class="btn btn-primary" style="font-family: 'Cookie', cursive; color: white; font-size: 25px; width: 120px;" value="Create"
               onclick="location.href='@Url.Action("Create", "Recipes")'" />
        <input type="button" class="btn btn-primary" style="font-family: 'Cookie', cursive; color: white; font-size: 25px; width: 160px; margin: 0 30px 0 30px;" value="Saved Recipes"
               onclick="location.href='@Url.Action("CooksSaved", "Recipes")'" />
        <input type="button" class="btn btn-primary" style="font-family: 'Cookie', cursive; color: white; font-size: 25px; width: 120px;" value="Following"
               onclick="location.href='@Url.Action("FOllowers", "Cook")'" />
    </div>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.IMGUrl)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Steps)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cook)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RecipeId"  style="font-family: 'Cookie'; font-size: 20px; color: rgb(13,10,77);">
                    @Html.DisplayFor(modelItem => item.RecipeName)
                    </a>
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.IMGUrl)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Ingredients)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Steps)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CookName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.RecipeId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.RecipeId">Delete</a> |
                    <a asp-action="SeeReviews" asp-route-id="@item.RecipeId">See Your Reviews</a> 
                </td>
            </tr>
        }
    </tbody>
    

</table>

WhatsCookinGroupCapstone/Views/Recipes/Search.cshtml
@model IEnumerable<WhatsCookinGroupCapstone.Models.Recipe>

@{
    ViewData["Title"] = "Search";
}

<h1 style="font-family: 'Cookie', cursive; font-weight: 600; font-size: 50px;">Search</h1>

<form asp-controller="Recipes" asp-action="Search" method="get">

    <p>
        <div class="form-inline">
            <input class="form-control mr-sm-2" type="text" style=" width: 50%;" name="SearchString">
            <input class="btn btn-primary my-sm-0" style=" font-family: 'Cookie' , cursive; color: white; font-size: 20px;" type="submit" value="Search" />
        </div>
    </p>
</form>

<table class="table container">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            <!--<th>-->
            @* @Html.DisplayNameFor(model => model.IMGUrl)*@
            <!--</th>-->
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Steps)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cook.UserName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="container">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RecipeId" style="font-family: 'Cookie'; font-size: 20px; color: rgb(13,10,77)">
                        @Html.DisplayFor(modelItem => item.RecipeName)
                    </a>
                </td>
                <!--<td>-->
                @*@Html.DisplayFor(modelItem => item.IMGUrl)*@
                <!--</td>-->
                <td>
                    @Html.DisplayFor(modelItem => item.Ingredients)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Steps)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CookName)
                </td>
                <td>
                    <a asp-action="SeeReviews" asp-route-id="@item.RecipeId">See All Reviews</a> |
                    <a asp-action="Review" asp-route-id="@item.RecipeId">Add a Review</a> |
                    <a asp-action="Details" asp-route-id="@item.RecipeId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>